### ISSUE TITLE
Assembly Jar contains Scala dependencies

### ISSUE THREAD

**Issue by gquintana** [CoxAutomotiveDataSolutions/spark-distcp#9]
Scala libraries present in the assembly conflict with Spark provided ones:

```
2022-01-14 08:46:19.371 [rpc-client-1-2] ERROR org.apache.spark.network.server.TransportRequestHandler - Error while invoking RpcHandler#receive() for one-way message.
java.lang.ClassCastException: cannot assign instance of scala.concurrent.duration.FiniteDuration to field org.apache.spark.rpc.RpcTimeout.duration of type scala.concurrent.duration.FiniteDuration in instance of org.apache.spark.rpc.RpcTimeout
        at java.base/java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2205)
        at java.base/java.io.ObjectStreamClass$FieldReflector.checkObjectFieldValueTypes(ObjectStreamClass.java:2168)
```

The following libraries should be excluded from assembly Jar:

* org.scala-lang.modules scala-collection-compat
* org.scala-lang scala-reflect
* org.scala-lang scala-library

**Comment by jamesfielder** [comment]
Fix merged now. I'll go through all of the PRs and issues and then likely release a new version with all the fixes. :)
